### ISSUE TITLE
Code attached is for Visual Studio

### ISSUE THREAD

**Issue by ankugarg** [OfficeDev/Excel-Add-in-Tutorial#4]
Code should be compatible with Visual Studio code as it's prerequisites mentioned here - https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial#step-1.

**Comment by lindalu-MSFT** [comment]
@ankugarg Can you clarify what you mean? Is the code missing? Or is there a bug in the documentation?

**Comment by Rick-Kirkham** [comment]
The sample was created with Visual Studio Code, so it is definitely compatible with Visual Studio Code.

**Comment by ankugarg** [comment]
@Rick-Kirkham 
Thanks, found the project compatible with Visual Studio code
