### ISSUE TITLE
is there a working example for ajax.get?

### ISSUE THREAD

**Issue by JanikSachs** [OfficeDev/Excel-Add-in-Tutorial#7]
I can't find anything for remote request in ExcelAddins.

**Comment by Rick-Kirkham** [comment]
This sample makes an ajax request to get a local file. Will that serve your needs?
https://github.com/OfficeDev/Excel-Add-in-JavaScript-SalesTracker/blob/6ff291402feeac15d028fd27b8d7e0ea1fb98c55/SalesTrackerWeb/Scripts/Helpers.js

**Comment by JanikSachs** [comment]
Thanks for the reply. I will look into it as soon as I get the time.

**Comment by JanikSachs** [comment]
Hey @Rick-Kirkham 
I tryed using the example. First of all here is my Code:
```
$.ajax({
            url: 'https://localhost:44330/api/ServerInfo/GetServerStartTime',
            dataType: "json"
        })
            // Process returned data.
            .then(function (data) {
                $('#label1').append(data);
            })
            .fail(function (xhr, textStatus, errorThrown) {
                $('#label1').append("Unable to get data: " + errorThrown);
            });
```
After making the call, it always jumps to fail, but the errorThrown is empty.

![image](https://user-images.githubusercontent.com/23638748/54996500-c2660f00-4fc9-11e9-8ac9-b1b42dbd2b2c.png)

Can you help  me with this?

**Comment by Rick-Kirkham** [comment]
Since the problem is not with the sample in this repo, please raise it on StackOverflow where the whole community will benefit from the answers that you get. Be sure to tag the question `office-js`. Thanks.

**Comment by JanikSachs** [comment]
It was a CORS problem. :/
